"""Turn an Outscraper Google-reviews export into src/reviews-data.js.

Usage:  python3 scripts/import-reviews.py path/to/Outscraper-export.xlsx

Only the fields the site shows are kept (name, rating, date, text, review link),
so the raw export (which has reviewer profile IDs and photos) never goes in the repo.
Tags below decide which pages a review can appear on. Reviews not listed in TAGS
are imported as general reviews; names in EXCLUDE are left out entirely.
"""
import json, re, sys
from datetime import datetime
import pandas as pd

# Which services each review talks about, and any town it can be featured on.
TAGS = {
    'CADL Videography': (['roofing'], []),
    'Julie Wollaston': (['velux'], []),
    'Kevin Sumner': (['velux'], []),
    'Maureen Gillen': (['velux'], []),
    'Neil Baker': (['velux'], []),
    'maxine millman': (['velux'], []),
    'Jennifer Webb': (['roofing', 'velux'], []),
    'Sue McGivern': (['velux'], []),
    'Rachel Yarham': (['roofing'], []),
    'David Twigger': (['roofing', 'leadwork'], []),
    'Jane Deacon': (['velux'], []),
    'P B': (['roofing'], []),
    'Daniel Warry': (['leadwork'], []),
    'Richard Mitchell': (['leadwork'], []),
    'Rachel Bullock': (['roofing'], []),
    'Helen Brindley': (['roofing', 'velux'], []),
    'Andrew Wood': (['velux'], []),
    'Lauren Tapp': (['velux'], []),
    'James Yarham': (['velux'], []),
    'Colin Baker': (['roofing'], []),
    'Bruce Rogers': (['velux'], []),
    'Arnaud LE LAN': (['roofing'], []),
    'Lee Johnson': (['velux'], []),
    'Kat Stainforth': (['roofing', 'velux'], []),
    'Kaz Martin': (['velux'], []),
    'Richard Hamer': (['leadwork'], []),
    'Jane Baker': (['roofing', 'leadwork'], []),
    'Ali Chadwick': (['velux'], []),
    'Sandra Law': (['roofing'], []),
    'Rosalind Lamble': (['velux', 'roofing', 'leadwork'], []),
    'Paul Douch': (['leadwork'], []),
    'Gail Johnson': (['velux'], []),
    'megan furneaux': (['velux'], []),
    'Jude Peace Portraits': (['velux'], []),
    'Simon Powell': (['roofing'], []),
    'Chris Tickle': (['velux', 'roofing'], []),
    'Rebecca Wollerton': (['roofing'], []),
    'Tim Durrant': (['velux'], []),
    'Ros Allen': (['velux'], []),
    'Tish England Design': (['velux'], []),
    'Anne Wakeham': (['velux'], []),
    'Nick Seddon': (['roofing', 'leadwork'], ['brixham']),  # says Kingswear
    'Nicky Allen': (['roofing'], []),
    'Colin Mather': (['velux', 'roofing'], []),
    'Josceline Leicester': (['velux', 'roofing'], []),
    'harry bear': (['velux'], []),
    'Luke Carnaby': (['roofing'], []),
    'Roger Lane': (['roofing', 'leadwork'], []),
    'Claire Sands': (['velux', 'roofing'], []),
    'Audrey Gooding': (['velux'], []),
    'Adrian Hines': (['velux'], []),
    'Tobz Malone': (['velux'], ['torquay', 'paignton', 'brixham']),  # says Torbay area
    'Andy Liddle': (['velux'], []),
    'Stephen Watson': (['roofing', 'velux'], []),
    'Richard Bennett': (['velux'], []),
}

# Left out: too short to be useful, or wording a business shouldn't republish.
EXCLUDE = {'Keran Spiller', 'Mary Hindle', 'David Sims', 'Neil Hanley'}

# Place names that appear in the review text itself (shown under the name).
PLACE = {'Nick Seddon': 'Kingswear', 'Tobz Malone': 'Torbay'}


def slug(s):
    return re.sub(r'[^a-z0-9]+', '-', s.lower()).strip('-')


def display_name(s):
    # Google shows some names in lower case ("harry bear"); title-case only those.
    return s.title() if s == s.lower() else s


def main(path):
    df = pd.read_excel(path)
    out = []
    for _, r in df.iterrows():
        name = str(r.author_title)
        if not isinstance(r.review_text, str) or name in EXCLUDE:
            continue
        services, towns = TAGS.get(name, ([], []))
        text = re.sub(r'\s*<br>\s*(<br>\s*)*', '\n', r.review_text.strip())
        text = re.sub(r'[ \t]{2,}', ' ', text)
        when = datetime.strptime(str(r.review_datetime_utc)[:10], '%m/%d/%Y')
        out.append({
            'id': slug(name),
            'name': display_name(name),
            'rating': int(r.review_rating),
            'date': when.strftime('%Y-%m'),
            'text': text,
            'url': r.review_link if isinstance(r.review_link, str) else None,
            'services': services,
            'towns': towns,
            'place': PLACE.get(name),
        })
    out.sort(key=lambda x: x['date'], reverse=True)
    first = df.iloc[0]
    summary = {
        'count': int(first.reviews),
        'average': round(float(df.review_rating.mean()), 1),
    }
    with open('src/reviews-data.js', 'w') as f:
        f.write('// Generated by scripts/import-reviews.py from the Google reviews export. Do not edit by hand.\n')
        f.write(f'export const reviewSummary = {json.dumps(summary)};\n')
        f.write(f'export const allReviews = {json.dumps(out, ensure_ascii=False, indent=1)};\n')
    print(f'{len(out)} reviews written ({len(df)} in export, {summary["average"]} average)')
    untagged = [x['name'] for x in out if not x['services']]
    print('General (no service tag):', ', '.join(untagged))


if __name__ == '__main__':
    main(sys.argv[1])
