// Generated by scripts/import-reviews.py from the Google reviews export. Do not edit by hand.
export const reviewSummary = {"count": 81, "average": 5.0};
export const allReviews = [
 {
  "id": "ali-chadwick",
  "name": "Ali Chadwick",
  "rating": 5,
  "date": "2026-05",
  "text": "Mark installed exterior shutter and interior blackout blind. His advice on the suitable products was great & the work carried out quickly. Highly recommended",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2kwMk4zTlRjRUZsYzJaWFdYZG5jbDlvTUVOTlZIYxAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOi02N3NTcEFlc2ZXWXdncl9oMENNVHc%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "sandra-law",
  "name": "Sandra Law",
  "rating": 5,
  "date": "2026-05",
  "text": "Scaffolding efficiently erected/ Sam Dixon and Todd were an admirable team - good communicators/ focussed and efficient in the 2 day work. Work completed to a high standard, They were very helpful in assessing unforeseen problems and dealing with them. We would most positively recommend the company.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2xwWFRXWkZUSGxHZFRGdE5HUjFNUzFvY25CaFkxRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOlpXTWZFTHlGdTFtNGR1MS1ocnBhY1E%7C%7C?hl=en-US",
  "services": [
   "roofing"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "paul-douch",
  "name": "Paul Douch",
  "rating": 5,
  "date": "2026-04",
  "text": "We had a leak coming from one of our chimneys, the leak had been misdiagnosed several times before by other trades which cost us time and money only for the leak to remain. I emailed Mark Dixon who although catching him at a busy time said he would send his son Sam around the next day. Sam accurately diagnosed the issue which unfortunately meant demolishing the granite chimney, removing the faulty lead tray and associated lead work and rebuilding the chimney. Mark recommended an excellent builder for the demolition and Sam returned to carry out the leadwork replacement which looks like a work of art ! Very pleased with the work carried out by Dixons Roofing and Leadwork. I would not hesitate to recommend Mark, Sam & Co. Many thanks.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT25Bd2QzUXRjelJLWm5jNFZrcERjVmhsUkRSVFgzYxAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOnAwd3QtczRKZnc4VkpDcVhlRDRTX3c%7C%7C?hl=en-US",
  "services": [
   "leadwork"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "kevin-ruff",
  "name": "Kevin Ruff",
  "rating": 5,
  "date": "2026-04",
  "text": "Professional, Courteous and a great job. I would use Dixons again",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2xnd1EzRjBla2d6WW5WbmMzVmxSa0ZYTURSYVlrRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOlgwQ3F0ekgzYnVnc3VlRkFXMDRaYkE%7C%7C?hl=en-US",
  "services": [],
  "towns": [],
  "place": null
 },
 {
  "id": "megan-furneaux",
  "name": "Megan Furneaux",
  "rating": 5,
  "date": "2026-04",
  "text": "Dixons Roofing and leadwork did an amazing job in replacing our very old Velux window, they are super efficient, very reliable and a lovely hard working team.\nWould definitely recommend!\nThank you",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2sxV1lrUjJiRGs0WkVZdE56SkNOVlJ5VDJGaVozYxAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOk1WYkR2bDk4ZEYtNzJCNVRyT2FiZ3c%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "chris-tickle",
  "name": "Chris Tickle",
  "rating": 5,
  "date": "2026-03",
  "text": "Mark and his team replaced two Velux windows, and sorted damaged roof tiles for us. They are highly professional, giving good advice, and always courteous and tidy on site. I would highly recommend them.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2tOaVZUVlhUMVUyV2sxNldYbFRWR1pRWWxobVltYxAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOkNiVTVXT1U2Wk16WXlTVGZQYlhmYmc%7C%7C?hl=en-US",
  "services": [
   "velux",
   "roofing"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "rebecca-wollerton",
  "name": "Rebecca Wollerton",
  "rating": 5,
  "date": "2026-03",
  "text": "Thank you to Mark and the rest of the team. Mark was very responsive, and diagnosed the source of our various roof leaks. The team were very polite and finished the job in good time. We were really impressed by the quality of the work, and the speed in which it was completed.\nWe would not hesitate to call on them again in the future. Thanks again.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT20xc1RtOTJSMDF3WVV4VGVXSkJlSFZpVTI1NWFVRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOm1sTm92R01wYUxTeWJBeHViU255aUE%7C%7C?hl=en-US",
  "services": [
   "roofing"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "tim-durrant",
  "name": "Tim Durrant",
  "rating": 5,
  "date": "2026-03",
  "text": "We gave Mark a challenge fixing some long ago fitted external roof window shutters, installed by another company, that had stopped working. The team put a lot of effort and research into finding a solution that avoided substantial costs. The work was very neatly done and the service was friendly, professional and excellent throughout. Thanks team, job well done.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT21KcmJVSnFaazVMVkUxd1J6VmpSVk00TTJrNGRsRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOmJrbUJqZk5LVE1wRzVjRVM4M2k4dlE%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "ros-allen",
  "name": "Ros Allen",
  "rating": 4,
  "date": "2026-03",
  "text": "Replacement of 9 ancient velux windows - Dixons’ service was professional, and helpful. A good company to work with.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT210V1NUTjJWVlp4Y2tWUloxQXRjekpUTkcweVZYYxAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOmtWSTN2VVZxckVRZ1AtczJTNG0yVXc%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "tish-england-design",
  "name": "Tish England Design",
  "rating": 5,
  "date": "2026-03",
  "text": "Totally 100% recommend! Great guys - fantastic service. I had 3 velux windows replaced and am really happy with the result. Nothing was too much trouble. Great workmanship and attention to detail, kept me informed along the way. Thanks so much!",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT25OSVlYaHBkR1JYWlZOSFRYaEdNbkJOYUdWRWNFRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOnNIYXhpdGRXZVNHTXhGMnBNaGVEcEE%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "anne-wakeham",
  "name": "Anne Wakeham",
  "rating": 5,
  "date": "2026-03",
  "text": "I’m so pleased I chose Mark Dixon for fitting my new velux windows. From start to finish all questions answered,totally professional, nothing has been too much trouble . A family business,his sons worked really hard to an excellent standard. Courteous tidy workers .\nVery happy to recommend,my dark bedroom has been transformed to a lovely bright room.\nMany thanks to Dixons Roofing and Leadwork",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT25OUmMyVTBWRFpoVEhGRFoydE9PRjkzWldJMVJrRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOnNRc2U0VDZhTHFDZ2tOOF93ZWI1RkE%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "sheree-ager",
  "name": "Sheree Ager",
  "rating": 5,
  "date": "2026-03",
  "text": "Mark was efficient courteous and did a great job for us, would recommend.him highly.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2xoSWFIcFdhMFJDWmw4MVQwRkJkbFJqT0habmFXYxAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOlhIaHpWa0RCZl81T0FBdlRjOHZnaWc%7C%7C?hl=en-US",
  "services": [],
  "towns": [],
  "place": null
 },
 {
  "id": "nick-seddon",
  "name": "Nick Seddon",
  "rating": 5,
  "date": "2026-03",
  "text": "Being a retired Charted surveyor, I am used to dealing with Tradesmen and what needed to be done to stop damp penetrating down into my living accommodation from an old porous brick chimney. I was impressed with Mark and his son from the outset – friendly helpful and knowledgeable ,with a lot of experience. How refreshing! They did a great job despite the dreadful weather and reasonably priced! I would have no hesitation in recommending them.\nNick Seddon ,Kingswear.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT21wcVgyRkliWE5vU1ZkelozRnFjR3RSU2xOeVFXYxAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOmpqX2FIbXNoSVdzZ3FqcGtRSlNyQWc%7C%7C?hl=en-US",
  "services": [
   "roofing",
   "leadwork"
  ],
  "towns": [
   "brixham"
  ],
  "place": "Kingswear"
 },
 {
  "id": "nicky-allen",
  "name": "Nicky Allen",
  "rating": 5,
  "date": "2026-03",
  "text": "Mark and the team at Dixons Roofing were first class.\nThey were incredibly kind when my mother’s roof started leaking during awful weather.\nThey went to so much trouble to help as quickly as they could, provided lots of information regarding the options available and then did exactly what they said they would do when they said they would do it.\nUpdates throughout the job, a brilliantly friendly team and great people to communicate with.\nI highly recommend them.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2xCc1NrMUNWMEV4Y0RnNFIwMW1UMmhTY0RGWGFGRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOlBsSk1CV0ExcDg4R01mT2hScDFXaFE%7C%7C?hl=en-US",
  "services": [
   "roofing"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "colin-mather",
  "name": "Colin Mather",
  "rating": 5,
  "date": "2026-03",
  "text": "The Dixon's did a very professional job making good poor work done by others; together with the efficient installation of replacement Velux window. Mark's communication at every stage was excellent. Highly recommended.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT21OTk9FeExkMkpaV0hScE5XSkxiSFl6ZW5KaFNuYxAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOmNNOExLd2JZWHRpNWJLbHYzenJhSnc%7C%7C?hl=en-US",
  "services": [
   "velux",
   "roofing"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "josceline-leicester",
  "name": "Josceline Leicester",
  "rating": 5,
  "date": "2026-03",
  "text": "We had a fantastic experience using Mark and his team, and would absolutely use again. We had a Velux window fitted in a very awkward position alongside chimney and roof repairs on our old Victorian house. Their work was outstanding, the guys sent to do the work were polite, helpful and informative. They are on our go to list should we have any further issues in the future an would highly recommend their work to anyone looking for an excellent team to do their roofing repairs.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2xWb1NHbHlhREIwTjJ3dFRrUldTMEpPTWpKU05rRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOlVoSGlyaDB0N2wtTkRWS0JOMjJSNkE%7C%7C?hl=en-US",
  "services": [
   "velux",
   "roofing"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "harry-bear",
  "name": "Harry Bear",
  "rating": 5,
  "date": "2026-03",
  "text": "We booked Dixon's Roofing as they are listed as an approved Velux specialist, and sure enough we received the best advice, a great price and a superb installation. Having had a Velux badly installed at a previous property, we didn't want to take the risk this time, and Mark and his team were excellent!",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2tNdFJuSkdabVZtTXpjNVYyWkVUM0JqYjI5a1NrRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOkMtRnJGZmVmMzc5V2ZET3Bjb29kSkE%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "luke-carnaby",
  "name": "Luke Carnaby",
  "rating": 5,
  "date": "2026-03",
  "text": "Mark and his team responded quickly, solved problems and provided good work on a tricky site. I wouldn't hesitate to use them again.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2xJMFJUbG5ZblJGUVRnelZETkVlV2R4VUhaSlEwRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOlI0RTlnYnRFQTgzVDNEeWdxUHZJQ0E%7C%7C?hl=en-US",
  "services": [
   "roofing"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "roger-lane",
  "name": "Roger Lane",
  "rating": 5,
  "date": "2026-03",
  "text": "Mark and his family team replaced our roof and rebuilt our chimney last summer. They were great to have around, worked efficiently, happily and tidily. The heavy rains and wind over the winter provided a great test of the roof and it passed with flying colours. The lead work on the valleys and chimney is extremely well done. The house had always had a slight residual smell of damp which has now gone. Highly recommended!",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2tkbExUSkxkREZCV0hSc1lraFRXRE14Y1d3ME1HYxAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOkdlLTJLdDFBWHRsYkhTWDMxcWw0MGc%7C%7C?hl=en-US",
  "services": [
   "roofing",
   "leadwork"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "adrian-hines",
  "name": "Adrian Hines",
  "rating": 5,
  "date": "2026-03",
  "text": "The team at Dixons Roofing replaced some Velux windows for us. They did a fantastic job, including having to deal with a number of additional complications that arose. They kept us informed throughout, and left everything clean and tidy. Very highly recommended!",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2pka00zUXRNMlpxU1hZd2NHODVOSE5XU3pkS1IyYxAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOjdkM3QtM2ZqSXYwcG85NHNWSzdKR2c%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "isobel-yandle",
  "name": "Isobel Yandle",
  "rating": 5,
  "date": "2025-11",
  "text": "Excellent job, very professional. Kept fully informed throughout. Conscientious, hard working and knowledgeable - a great team. Very pleased with the results.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2xsSUxVOWxkbFUzV0dwa2ExcFNOamhxUkVsemFGRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOllILU9ldlU3WGpka1pSNjhqRElzaFE%7C%7C?hl=en-US",
  "services": [],
  "towns": [],
  "place": null
 },
 {
  "id": "richard-hamer",
  "name": "Richard Hamer",
  "rating": 5,
  "date": "2025-07",
  "text": "On the very first visit to quote, The Dixons quickly identified problems on a section of lead roof that we, our surveyor, and other roofing firms had all believed to be the \"good\" bit of roof. Their instincts proved to be correct. We saw with our own eyes the state of the rotting plywood base and badly corroded lead underside which was pulled away, once the work was started.\nWe were impressed with the quality of the workmanship. They were able to weld perfectly fitting leadwork in situ, clearly taking a great deal of pride in their work. They kept us informed every step of the way and it was a pleasure having them around. There were no unexpected items of work added on, and significant extras that I myself requested were cheerfully accommodated at a fair price.\nWe would not hesitate to recommend Dixons Roofing & Leadwork. Mark, Sam, Andy & Todd make a great team and we would like to thank them all for their hard work, professionalism, and positive attitudes.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2tOVVkzVTRiRGhCWmsxc1NWTk9lVlE0UjJwS1RsRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CAIQACodChtycF9oOkNUY3U4bDhBZk1sSVNOeVQ4R2pKTlE%7C%7C?hl=en-US",
  "services": [
   "leadwork"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "rosalind-lamble",
  "name": "Rosalind Lamble",
  "rating": 5,
  "date": "2025-05",
  "text": "Excellent workmanship and professional team. Thank you for your hard work and transforming the roof on our home with new Velux, full replacement of concrete tiles to slate and leadwork",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnTUNZeWFYamN3EAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgMCYyaXjcw%7C%7C?hl=en-US",
  "services": [
   "velux",
   "roofing",
   "leadwork"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "david-twigger",
  "name": "David Twigger",
  "rating": 5,
  "date": "2024-11",
  "text": "Highly recommended. Mark and his team efficiently repaired our roof which was leaking behind a chimney, requiring replacement timbers, leadwork and tiling. Fairly priced, excellent quality, completed in the timescale originally indicated and a pleasure to deal with.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChdDSUhNMG9nS0VJQ0FnSUMzbXZiTm9nRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIC3mvbNogE%7C%7C?hl=en-US",
  "services": [
   "roofing",
   "leadwork"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "jane-deacon",
  "name": "Jane Deacon",
  "rating": 5,
  "date": "2024-10",
  "text": "When this company came to replace my two big old Velux windows and blackout blinds I felt reassured by the fact that they are an accredited Velux installer. They came as arranged and completed the job professionally to a high standard. They cleaned up all the mess and took away the old windows and packaging. Because I was happy with the completed job I have asked them to do a much bigger project for me and they’ll be starting this in the near future.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSURuazRUa0N3EAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDnk4TkCw%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "daniel-warry",
  "name": "Daniel Warry",
  "rating": 4,
  "date": "2024-10",
  "text": "Very happy. This was just a day's work fitting new lead flashings around my utility extension. Mark was very obliging squeezing the job in between other work they had going on. Good communications all round and efficient work on site. I work as a local Architect, and would be quite happy to put Dixons on our \"approved contractor\" list.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChdDSUhNMG9nS0VJQ0FnSURud3BTUXJ3RRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDnwpSQrwE%7C%7C?hl=en-US",
  "services": [
   "leadwork"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "richard-mitchell",
  "name": "Richard Mitchell",
  "rating": 5,
  "date": "2024-10",
  "text": "Mark and his team replaced our old leaking lead chimney flashings and the work was completed quickly and efficiently despite awkward access. The result is very good, Mark and the team were brilliant and I will definitely call them again if I require further work on our roof.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSURueUtyaFRnEAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDnyKrhTg%7C%7C?hl=en-US",
  "services": [
   "leadwork"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "rachel-bullock",
  "name": "Rachel Bullock",
  "rating": 5,
  "date": "2024-10",
  "text": "Having used Dixons Roofing on a few occasions, I have found them to be very reliable and very tidy and would recommend them for any roofing issues.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChdDSUhNMG9nS0VJQ0FnSURuOFBlTzBnRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDn8PeO0gE%7C%7C?hl=en-US",
  "services": [
   "roofing"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "helen-brindley",
  "name": "Helen Brindley",
  "rating": 5,
  "date": "2024-10",
  "text": "Mark and his team replaced our slate roof and velux windows in 2023-24 and did a fantastic job. They were hard working and reliable, completely trustworthy, consulted us about all aspects of the work and gave sensible advice. I have no reservations in recommending them.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChdDSUhNMG9nS0VJQ0FnSURuOE9LNi1BRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDn8OK6-AE%7C%7C?hl=en-US",
  "services": [
   "roofing",
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "andrew-wood",
  "name": "Andrew Wood",
  "rating": 5,
  "date": "2024-10",
  "text": "We had six velux windows replaced by Mark and the results were excellent. He gave us good advice on which windows to choose and it has definitely improved our property. We would recommend.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSURuME1UX1lREAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDn0MT_YQ%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "lauren-tapp",
  "name": "Lauren Tapp",
  "rating": 5,
  "date": "2024-10",
  "text": "We had leaking roof windows, so Mark and his team, replaced with velux. They did the job super quick and to a high standard. They were very polite and cleaned up after job. Mark communicated well both before and after job, I would highly recommend Mark Dixon",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChdDSUhNMG9nS0VJQ0FnSUNuX19TamtnRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgICn__SjkgE%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "terry-brown",
  "name": "Terry Brown",
  "rating": 5,
  "date": "2023-08",
  "text": "Mark is very reliable, trustworthy and will discuss with you the best solutions to problems and issues.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSURwOTUtNUN3EAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDp95-5Cw%7C%7C?hl=en-US",
  "services": [],
  "towns": [],
  "place": null
 },
 {
  "id": "emma-banks",
  "name": "Emma Banks",
  "rating": 5,
  "date": "2023-08",
  "text": "From Start to finish, excellent work. Exceptional service, meticulous in every way. Thank you Mark and your team\nGitcombe House and Country Cottages\nThe Gitcombe Estate",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSURwcV83UWJREAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDpq_7QbQ%7C%7C?hl=en-US",
  "services": [],
  "towns": [],
  "place": null
 },
 {
  "id": "sarah-bee",
  "name": "Sarah Bee",
  "rating": 5,
  "date": "2023-08",
  "text": "Nothing was too much trouble for Mark..he listened to my concerns re the job, and worked hard to achieve results.. much appreciated and highly recommend!",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSUNwbjh1T0lnEAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgICpn8uOIg%7C%7C?hl=en-US",
  "services": [],
  "towns": [],
  "place": null
 },
 {
  "id": "arnaud-le-lan",
  "name": "Arnaud LE LAN",
  "rating": 5,
  "date": "2023-08",
  "text": "Good job done by Mark and his team. Good professional and good advise. Not to hesitate if you have job to get done on your roof.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSUNwbjZPMUR3EAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgICpn6O1Dw%7C%7C?hl=en-US",
  "services": [
   "roofing"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "lee-johnson",
  "name": "Lee Johnson",
  "rating": 5,
  "date": "2023-08",
  "text": "Professional and neat roofing work fitting a Velux balcony window and a Velux roof window.\nA great friendly company. Would highly recommend them.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSUNwbjVIbkF3EAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgICpn5HnAw%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "kat-stainforth",
  "name": "Kat Stainforth",
  "rating": 5,
  "date": "2023-08",
  "text": "Mark and his team did an amazing job replacing our slate roof, damaged timbers, and several Velux windows. Mark was brilliant from the outset - super responsive, friendly and professional. He kept in touch with us about the start date for the work and kept us updated throughout, and made sure to explain and check with us any additional work he found that needed doing. The work was completed quickly and to a very high standard, with everything left impeccably clean and tidy. My wife and I both work from home so were around throughout the work, and Mark and his team were incredibly kind, respectful, professional and polite throughout. The roof and windows look amazing. It's rained non-stop since the work was completed and we've had no issues whatsoever. Mark and the rest of the guys made the whole process incredibly stress-free, and we are so grateful to them! 110% recommend.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSUNwbjliWVpnEAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgICpn9bYZg%7C%7C?hl=en-US",
  "services": [
   "roofing",
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "paul-cater",
  "name": "Paul Cater",
  "rating": 5,
  "date": "2023-08",
  "text": "From start to finish these guys were a pleasure to have working. Quiet, clean and efficient they did the job brilliantly and I wholeheartedly recommend this company without reservation",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSUNwbl9yY0tBEAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgICpn_rcKA%7C%7C?hl=en-US",
  "services": [],
  "towns": [],
  "place": null
 },
 {
  "id": "nick-bosanko",
  "name": "Nick Bosanko",
  "rating": 5,
  "date": "2023-03",
  "text": "Superb company. Great communication at all times. They are real craftsmen. Would recommend with no hesitation.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSUNSeUl6VEhBEAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgICRyIzTHA%7C%7C?hl=en-US",
  "services": [],
  "towns": [],
  "place": null
 },
 {
  "id": "john-mills",
  "name": "John Mills",
  "rating": 5,
  "date": "2023-03",
  "text": "Mark and his team are thorough, professional and very helpful. They do a proper job. Very happy with the work and service they provide.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSURHNDQzVUtBEAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDG443UKA%7C%7C?hl=en-US",
  "services": [],
  "towns": [],
  "place": null
 },
 {
  "id": "tobz-malone",
  "name": "Tobz Malone",
  "rating": 5,
  "date": "2023-02",
  "text": "Mark and the team fitted 2 velux windows to my property recently, they were very professional and knowledgeable in their approach, arrived on time and are acredited Velux installers, they provided detailed photos of the install stages for submission for any planning regs needed and the quality of workmanship was to a high and exacting standard. Very happy with the work and would use again. I highly recommend for the Torbay area.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSUNoajczSkZ3EAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIChj73JFw%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [
   "torquay",
   "paignton",
   "brixham"
  ],
  "place": "Torbay"
 },
 {
  "id": "philip-hodson",
  "name": "Philip Hodson",
  "rating": 5,
  "date": "2023-02",
  "text": "Very prompt response to my initial enquiry. Job done within a few days after receipt of order. Clean and efficient workers.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSUNobDhQeERnEAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIChl8PxDg%7C%7C?hl=en-US",
  "services": [],
  "towns": [],
  "place": null
 },
 {
  "id": "andy-liddle",
  "name": "Andy Liddle",
  "rating": 5,
  "date": "2023-02",
  "text": "Mark and his lads replaced a rotten Velux for us. They were clean, tidy, polite, did a great job on time and to budget. One of Mark's lads even went as far as to help me paint a hard to get to place on my chimney stack while he was on the roof. Highly recommended.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSUNobDYyR1pBEAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIChl62GZA%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "stephen-watson",
  "name": "Stephen Watson",
  "rating": 5,
  "date": "2023-02",
  "text": "We were extremely pleased with all aspects of the work performed by Mark and his team. They re-slated the roof of a 200 year old cottage including replacement of two Velux windows (one was 1.2m across) and a flat roof extension. Several rotting beams were discovered. The roof was warped making it far from routine. The team did a fantastic job in all respects and we could not be more pleased with the product. Mark kept us informed of progress at all times and responded rapidly to questions and showed flexibility when needed. The team are very hard-working and tidy. We felt that the work was very good value and would not hesitate to use them again.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChdDSUhNMG9nS0VJQ0FnSUNobDdyc3ZRRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIChl7rsvQE%7C%7C?hl=en-US",
  "services": [
   "roofing",
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "richard-bennett",
  "name": "Richard Bennett",
  "rating": 5,
  "date": "2023-02",
  "text": "Mark and his team installed two Velux windows for us back in December 2022 and we couldn't be happier with the result and frankly wouldn't consider looking for anyone else should we ever need more windows or work doing to our roof.\nTheir pricing was competitive and they turned up when promised and despite working in very frosty conditions, managed to install the windows without need for scaffolding which clearly saved on cost. They clearly know their stuff and were very professional throughout. Highly recommended.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChdDSUhNMG9nS0VJQ0FnSUNobDdLeG1RRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIChl7KxmQE%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "rachel-yarham",
  "name": "Rachel Yarham",
  "rating": 5,
  "date": "2022-11",
  "text": "Mark and his team replaced our roof earlier this year. They were professional, knowledgeable and friendly. Their quote was very reasonable and the work of a very high standard. We had to wait a a while for them but it was worth the wait, they also replaced our roof during a very cold winter! We wouldn't hesitate to recommend them.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChdDSUhNMG9nS0VJQ0FnSUMtLWVINGlnRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIC--eH4igE%7C%7C?hl=en-US",
  "services": [
   "roofing"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "jane-baker",
  "name": "Jane Baker",
  "rating": 5,
  "date": "2022-07",
  "text": "Just wanted to express my appreciation for the re-roofing of my house. You solved the problem of the low pitched dormer, solved my chimney weaknesses and did a lovely job on a difficult terraced roof.\nEveryone is commenting on the beautiful leadwork in the valley. You are extremely competent, honest and professional. I have been highly recommending you to everyone.\nThank you for a fine job.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSURPcW9UZmN3EAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDOqoTfcw%7C%7C?hl=en-US",
  "services": [
   "roofing",
   "leadwork"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "gail-johnson",
  "name": "Gail Johnson",
  "rating": 5,
  "date": "2022-04",
  "text": "Mark and his team replaced our Velux windows and they were outstanding. They were professional and friendly at all times and overall did a great job. They even offered to try and help capture a squirrel that had been chased into the house by our cat! We would definitely recommend them. Five stars well earned.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSUMyd1lhTWJBEAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIC2wYaMbA%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "laura-moralee",
  "name": "Laura Moralee",
  "rating": 5,
  "date": "2022-04",
  "text": "Mark and his team were brilliant, really professional and worked really hard. Rates were very fair and we were really pleased that they did our job for us.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSUMyOEt2c0hBEAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIC28KvsHA%7C%7C?hl=en-US",
  "services": [],
  "towns": [],
  "place": null
 },
 {
  "id": "jude-peace-portraits",
  "name": "Jude Peace Portraits",
  "rating": 5,
  "date": "2022-04",
  "text": "Mark and his team worked incredibly hard to stick to promised fitting dates of our Velux windows. They were professional, efficient, tidy and went that extra distance to address all issues that arose along the installation process. Very please with their work .. 5 velux windows installed .. it’s transformed our 2 top loft rooms very pleased thank you all. 👍🏻",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSURXMS11OEVnEAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDW1-u8Eg%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "simon-powell",
  "name": "Simon Powell",
  "rating": 5,
  "date": "2022-04",
  "text": "We used Mark’s company on 2 occasions for roof repair, one of which was due to storm damage. The whole team was professional, knowledgeable and friendly. They came quickly and could not have been more helpful. I would not hesitate to use their services again.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSURXbmFxblN3EAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDWnaqnSw%7C%7C?hl=en-US",
  "services": [
   "roofing"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "cadl-videography",
  "name": "CADL Videography",
  "rating": 5,
  "date": "2021-12",
  "text": "We were very impressed with the service and quality of work provided by Mark Dixon and his team. Not only were they professional and efficient, they were also extremely friendly. Persistent roof leak finally solved! Highly recommended. Many thanks.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChdDSUhNMG9nS0VJQ0FnSUNtMkpHdmtnRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgICm2JGvkgE%7C%7C?hl=en-US",
  "services": [
   "roofing"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "julie-wollaston",
  "name": "Julie Wollaston",
  "rating": 5,
  "date": "2021-12",
  "text": "I highly recommend Mark and his team. We had two velux windows installed in a new loft conversion. All done in a couple of days, great job!",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSURHdzhPRGJBEAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDGw8ODbA%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "kevin-sumner",
  "name": "Kevin Sumner",
  "rating": 5,
  "date": "2021-12",
  "text": "Mark, Sam & Tod installed a new Velux window for us and replaced a 30yr old one too. The preparation, installation, communication and quality of the jobs was all first rate. These gentlemen are top of their game and I cannot recommend them highly enough. Well done!",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChdDSUhNMG9nS0VJQ0FnSURHbmNYUG5RRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDGncXPnQE%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "maureen-gillen",
  "name": "Maureen Gillen",
  "rating": 5,
  "date": "2021-11",
  "text": "Mark and his family did a first class job of installing two Velux windows into two separate rooms in our home (in a sloped roof). Mark's communication from start to finish was absolutely excellent and the whole job was faultless. They all worked extremely hard to complete the job. We would have no hesitation whatsoever in recommending this family company.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChdDSUhNMG9nS0VJQ0FnSURHdHZhMGt3RRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDGtva0kwE%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "neil-baker",
  "name": "Neil Baker",
  "rating": 5,
  "date": "2021-11",
  "text": "Mark, Sam and Todd replaced two very large Velux windows for us.\nTheir workmanship was exceptional. They arrived when they said they would, ensured every inch of the inside workspace and route to it were covered prior to starting work and cleaned and hoovered on completion. They completed the work quickly and efficiently keeping us informed as they went. They even went the extra mile by replacing some existing broken tiles. They were professional, polite, helpful and friendly. We’re delighted with their work and would not hesitate to use them again or recommend them to others.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChdDSUhNMG9nS0VJQ0FnSURHMnRfeDJBRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDG2t_x2AE%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "maxine-millman",
  "name": "Maxine Millman",
  "rating": 5,
  "date": "2021-11",
  "text": "Absolutely excellent from start to finish. Mark couldn’t have been more helpful with suggesting the right way to go with choosing our Velux windows. No pushiness just genuine helpful advice. The team fitting the windows were really professional and went above and beyond what they were asked to do. They carried out the work most efficiently and left the room clean and tidy. The windows look great and the addition of blackout blinds is perfect. Genuine value for money. I would definitely recommend Dixon’s.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSURHMnJPYVhnEAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDG2rOaXg%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "jennifer-webb",
  "name": "Jennifer Webb",
  "rating": 5,
  "date": "2021-11",
  "text": "Would highly recommend Mark and his team. A really professional outfit. Dependable and hard working. Extremely pleased with the standard of roof they replaced and help on deciding on velux windows.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChdDSUhNMG9nS0VJQ0FnSURHbXI3Vi1BRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDGmr7V-AE%7C%7C?hl=en-US",
  "services": [
   "roofing",
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "graham-may",
  "name": "Graham May",
  "rating": 5,
  "date": "2021-11",
  "text": "Excellent service, willing and able to fit in the work according to our needs. The work was carried out to a very high standard and on time. The three tradesmen working on the job were all very obliging and friendly.\nWould definitely use them again and are only to pleased to recommend them.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSURHbXVqR0N3EAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDGmujGCw%7C%7C?hl=en-US",
  "services": [],
  "towns": [],
  "place": null
 },
 {
  "id": "sue-mcgivern",
  "name": "Sue McGivern",
  "rating": 5,
  "date": "2021-11",
  "text": "Excellent service given by Mark Dixon and his team when they installed a replacement Velux window for me.\nThroughout the process they showed wonderful customer service providing local knowledge regarding extra slates required, type of window suitable and timescale.\nI would employ his team without hesitation for any other jobs of this nature.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChdDSUhNMG9nS0VJQ0FnSURHNnVQTnRBRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDG6uPNtAE%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "bruce-rogers",
  "name": "Bruce Rogers",
  "rating": 5,
  "date": "2021-08",
  "text": "Arrived on time, polite, efficient, good attention to detail, professional, helpful and very happy with the final result. Would definitely recommend Mark and his team to anyone needing a new Velux window.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSURhMUo2NWNREAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDa1J65cQ%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "keith-hardie",
  "name": "Keith Hardie",
  "rating": 5,
  "date": "2021-08",
  "text": "Mark and his team were outstanding, a true professional, highly skilled, very dependable and a pleasure to have doing the work for me.\nI would have no hesitation in recommending Mark and give a 💯 % positive rating.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSURhbUtIamRnEAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDamKHjdg%7C%7C?hl=en-US",
  "services": [],
  "towns": [],
  "place": null
 },
 {
  "id": "kaz-martin",
  "name": "Kaz Martin",
  "rating": 5,
  "date": "2021-07",
  "text": "Mark and his team were professional, tidy and did a wonderful job installing two Velux windows in our son's bedroom which is no mean feat as it's a really old part of the house and the beams made it a tricky installation.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChdDSUhNMG9nS0VJQ0FnSUNhME1qV3p3RRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgICa0MjWzwE%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "steve-fowle",
  "name": "Steve Fowle",
  "rating": 5,
  "date": "2021-07",
  "text": "Mark and his team were a joy to work with.\nWe were delighted with the outcome and would recommend them to anyone.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChdDSUhNMG9nS0VJQ0FnSUNhNExuZ2h3RRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgICa4LnghwE%7C%7C?hl=en-US",
  "services": [],
  "towns": [],
  "place": null
 },
 {
  "id": "claire-sands",
  "name": "Claire Sands",
  "rating": 5,
  "date": "2021-03",
  "text": "Brilliant service!! Turned up earlier than we expected and fitted our window perfectly. They even repaired some ridge tiles while they here..... would 100% recommend.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSUR5Xy1ubUx3EAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDy_-nmLw%7C%7C?hl=en-US",
  "services": [
   "velux",
   "roofing"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "audrey-gooding",
  "name": "Audrey Gooding",
  "rating": 5,
  "date": "2021-03",
  "text": "We had 2 large velux windows replaced, great job, very pleased with result, carried out on time and everything explained in detail, left clean and tidy. Would definitely recommend this family crew.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSUR5cjdtM05REAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDyr7m3NQ%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "paula-proctor",
  "name": "Paula Proctor",
  "rating": 5,
  "date": "2021-03",
  "text": "Very professional, explained the work required and carried it out efficiently when they said they would. Competively priced, will recommend and use again.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSUR5cV9XWVdREAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDyq_WYWQ%7C%7C?hl=en-US",
  "services": [],
  "towns": [],
  "place": null
 },
 {
  "id": "michael-cooper",
  "name": "Michael Cooper",
  "rating": 5,
  "date": "2020-10",
  "text": "Fair price, turned up on the agreed date, did the agreed work to a very high standard, wish all businesses were this good.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChdDSUhNMG9nS0VJQ0FnSUNpMnRPZi1BRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgICi2tOf-AE%7C%7C?hl=en-US",
  "services": [],
  "towns": [],
  "place": null
 },
 {
  "id": "p-b",
  "name": "P B",
  "rating": 5,
  "date": "2020-10",
  "text": "Brilliant company, stunning work, very professional, lovely guys to have on site. Built roof on new extension",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSURDbGE2NWF3EAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDCla65aw%7C%7C?hl=en-US",
  "services": [
   "roofing"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "james-yarham",
  "name": "James Yarham",
  "rating": 5,
  "date": "2020-09",
  "text": "Mark recently installed a new velux for us, he is reliable, professional and undertakes good quality clean and tidy work",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSURDa2VlME1nEAE!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDCkee0Mg%7C%7C?hl=en-US",
  "services": [
   "velux"
  ],
  "towns": [],
  "place": null
 },
 {
  "id": "colin-baker",
  "name": "Colin Baker",
  "rating": 5,
  "date": "2020-09",
  "text": "Exceptional experience with this family run business, great communication and work of a high quality, I have complete trust in Mark and his team, I won't be going anywhere else for my Roofing needs and fully recommend them.",
  "url": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChdDSUhNMG9nS0VJQ0FnSURDb2Yta3hnRRAB!2m1!1s0x0:0xd7bf557054b23ce2!3m1!1s2@1:CIHM0ogKEICAgIDCof-kxgE%7C%7C?hl=en-US",
  "services": [
   "roofing"
  ],
  "towns": [],
  "place": null
 }
];
